"use client"

import Head from "next/head";
import Container from "react-bootstrap/Container";
import Header from "@/components/Header";
import Row from 'react-bootstrap/Row';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next.js Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
  integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
  crossOrigin="anonymous"
/>
      </Head>
      <Container as="main" className="py-4 px-3 mx-auto">
        <Header />

        <h1>Start</h1>
        More info coming soon.

        <Container>
      <Row>
      </Row>
    </Container>
      </Container>
    </>
  );
}